### ISSUE TITLE
Including a license

### ISSUE THREAD

**Issue by maxovb** [tuvovan/HDRI-debevec-Python#1]
Hey,

I wanted to use your code for some project, but unfortunately I can't because it doesn't have a license. Without a license, the repository has all rights reserved and is not open source. 

Would you consider adding a license to make it available to others ? You can use this website to help you choose: https://choosealicense.com/](url)

**Comment by maxovb** [comment]
Forget about it, I didn't read the readme correctly. You already have a license ;) Thanks !

**Comment by tuvovan** [comment]
would you mind to mention my name in your project? thanks!

**Comment by maxovb** [comment]
Hey, off course that if I use your code in a final version of the project I will mention it.
